FROM python:3.11-slim

WORKDIR /app

# Enable unbuffered python logs
ENV PYTHONUNBUFFERED=1

COPY pyproject.toml poetry.lock* ./

RUN python -m pip install "pymongo[srv]" && \
    python -m pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi

# Copiamos o código do backend
COPY dsr_rag.py .
COPY main.py .

# A porta que o Uvicorn usará (8000)
EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
